### ISSUE TITLE
Reduce UI extension size

### ISSUE THREAD

**Issue by leoluz** [argoproj-labs/argocd-extension-metrics#19]
Currently the UI extension has approx. 1 Mb. We should optimize and reduce the size of this file.

**Comment by alexmt** [comment]
I suspect you are bundling `ReactDOM`.  Try adding it to externals in webpack config: https://github.com/argoproj-labs/argocd-extension-metrics/blob/786aabee4fd71218561fd1203f4d508bdc01a917/extensions/resource-metrics/resource-metrics-extention/ui/webpack.config.js#L21

ReactDOM is injected by Argo CD as a global variable starting from v2.5.4 https://github.com/argoproj/argo-cd/commit/67ae39e99def037a1c6a21030feebe54ad7ba39d

**Comment by leoluz** [comment]
fixed
