### ISSUE TITLE
No tab Metrics

### ISSUE THREAD

**Issue by autokilla47** [argoproj-labs/argocd-extension-metrics#58]
Installed argocd-extension-metrics:
`kustomize build ./manifests | kubectl apply -f - --namespace=argocd`
 but there is no tab Metrics.
![image](https://github.com/argoproj-labs/argocd-extension-metrics/assets/49757910/221a91df-46fd-4a35-ab8e-42fd5b11d1cc)
Maybe there were some other steps that needed to be completed for installation?

argocd-extension-metrics: latest
argocd-extensions: v0.2.1
argocd: v2.8.4+c279299

**Comment by ofirshaya** [comment]
you need to install the sidecart container in the argocd-server deployment

https://github.com/argoproj-labs/argocd-extension-metrics#install-ui-extension

**Comment by leoluz** [comment]
Closing this for now as the installation instructions were updated in the main README file in this repo.
Please reopen if the issue remains.
