### ISSUE TITLE
Changes in documentation and other things

### ISSUE THREAD

**Issue by Amet13** [argoproj-labs/argocd-extension-metrics#6]
Hey.
Thanks for the useful extension.

I tried to install it following the current documentation in README and there are some thinks that probably should be updated.

## First thing

According [this](https://github.com/argoproj-labs/argocd-extension-metrics/blob/main/README.md#quick-start) we use the link to tarball that isn't in raw format:
```
$ kd ArgoCDExtension argocd-metrics-ext | grep Spec -A10 
Spec:
  Sources:
    Web:
      URL:  https://github.com/argoproj-labs/argocd-extension-metrics/blob/main/manifests/extension.tar
Status:
  Conditions:
    Message:  failed to download sources: archive/tar: invalid tar header
    Status:   "False"
    Type:     Ready
Events:       <none>
```

Replacing URL with direct raw file works:
```
$ kd ArgoCDExtension argocd-metrics-ext | grep Spec -A10
Spec:
  Sources:
    Web:
      URL:  https://github.com/argoproj-labs/argocd-extension-metrics/raw/e161a9262a59b4d3405527bf6ab3a2f47e4e61d4/manifests/extension.tar
Status:
  Conditions:
    Message:  Successfully processed 1 extension sources
    Status:   "True"
    Type:     Ready
Events:       <none>
```

I believe it could be permanently fixed by using github releases, for example like here: https://github.com/argoproj-labs/rollout-extension/

## Second thing

According the same README to install extension to k8s we have to apply `install.yaml` but it's not enough, we have to apply configmap as well, I believe the configmap should be included into `install.yaml` to README could be changed with instructions to install configmap before deployment/service.

## Third thing

Argocd-metrics-server is running in debug mode:

```
$ k logs -f argocd-metrics-server-798d99449-hjht4
...
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)
...
```

Is there any way to disable debug mode?

## Fourth thing

Even when I installed everything, I can't see any plots in ArgoCD:

<img width="1081" alt="Screenshot 2022-09-07 at 21 23 53" src="https://user-images.githubusercontent.com/5184847/188951110-ccdb5221-8f90-4bb1-9314-f1a2b6dfcce7.png">

Is there any way to debug it, what could be wrong there? Need to mention that the deployment runs on external k8s cluster and metrics-server is on the source ArgoCD cluster.

**Comment by remi-hackle** [comment]
@Amet13 
I'm also having the same problem, have you solved it?

**Comment by Amet13** [comment]
Unfortunately not, I stopped using this extension

**Comment by remi-hackle** [comment]
That's right, I think it'll be useful too, so I'm installing and setting it up, but there aren't too many data.
