### ISSUE TITLE
`dashboards 404 Not Found` - "No metrics to display"

### ISSUE THREAD

**Issue by harrywm** [argoproj-labs/argocd-extension-metrics#63]
Hello!

I've gone about installing the extension to allow our developers an (experimental) "single pane of glass" view of their deployments. I'm running into an issue where the `metrics` tab simply displays "No metrics to display", where, on closer inspection, the `dashboards` request to is returning a `404` when trying to pull in what I assume is a JSON blob for the applicable graphs.

![image](https://github.com/argoproj-labs/argocd-extension-metrics/assets/60188811/7b4ce3f0-2b28-41c8-a92c-5b0e2399d3c3)

The installation I've gone about setting up is as follows, using the `argo-extension-installer` with the Argo Helm charts, and the manifests included in this repository.

ArgoCD Helm values:
![Screenshot 2023-11-20 at 12 01 31](https://github.com/argoproj-labs/argocd-extension-metrics/assets/60188811/46bbbb53-178b-47e4-8801-ad1ddfd356fa)

Metrics-sever manifests (altered to use a more representative name for our cluster) - note, i've tried with both `TLS` enabled and disabled:
Deployment,
![Screenshot 2023-11-20 at 12 02 27](https://github.com/argoproj-labs/argocd-extension-metrics/assets/60188811/d3f76218-f153-4c68-9d00-6f3c6a9eef84)

Service,
![Screenshot 2023-11-20 at 12 02 58](https://github.com/argoproj-labs/argocd-extension-metrics/assets/60188811/7e6d31c6-cc39-4648-a427-620ba062de19)

Would appreciate some help as to where we're going wrong here. I've port-forwarded the metrics-server service locally, and pinged a representative endpoint (`metrics/api/applications/reloader/groupkinds/pod/dashboards`) and got JSON in return, so I'm assuming it's connectivity between Argo and the Metrics-Server, or some misconfiguration of a URL somewhere.

**Comment by mcanevet** [comment]
Same issue here. I can see this error message in argocd-server's logs:
`"read message err: websocket: close 1001 (going away)"` or `"read message err: websocket: close 1005 (no status)"`.
Interesting fact: when I remove the service in front of the argocd-metrics-server, I don't get this messages, so I guess argocd-server actually tries to communicate with argocd-metrics-server, but somehow the websocket is closed.

**Comment by ofirshaya** [comment]
could it be the difference in url in the stored artifacts and the pulling of the artifacts?

/api/applications/:application/groupkinds/:groupkind/rows/:row/graphs/:graph [here](https://github.com/argoproj-labs/argocd-extension-metrics/blob/82d8690f447da75f181191ec1051d89dda8ad27c/internal/server/server.go#L107)

/extensions/metrics/api/applications/${applicationName}/groupkinds/${resourceType.toLowerCase()}/dashboards [here](https://github.com/argoproj-labs/argocd-extension-metrics/blob/82d8690f447da75f181191ec1051d89dda8ad27c/extensions/resource-metrics/resource-metrics-extention/ui/src/Metrics/client.ts#L23)

**Comment by ofirshaya** [comment]
I think its related to this:

How to Avoid 403 Errors for Missing Applications[¶](https://argo-cd.readthedocs.io/en/stable/developer-guide/api-docs/#how-to-avoid-403-errors-for-missing-applications)
All endpoints of the Applications API accept an optional project query string parameter. If the parameter is specified, and the specified Application does not exist, or if the Application does exist but is not in the given project, the API will return a 404 error.

[link](https://argo-cd.readthedocs.io/en/stable/developer-guide/api-docs/#applications-api) to documentation

**Comment by ofirshaya** [comment]
@leoluz any chance you can take a look?

**Comment by leoluz** [comment]
404 can be caused by 2 things:
1. Proxy extension isn't enabled in your Argo CD API server. In order to do so please follow this document: https://argo-cd.readthedocs.io/en/stable/developer-guide/extensions/proxy-extensions/#configuration
2. Argo CD metrics server is not configured properly.

I suspect that this is caused by `#1` so please, ensure that the feature flag is enabled. If the proxy extension feature is enabled you should be able to see the following entry in the API Server logs:
`Registering extensions... `

**Comment by harrywm** [comment]
> 404 can be caused by 2 things:
> 
> 1. Proxy extension isn't enabled in your Argo CD API server. In order to do so please follow this document: https://argo-cd.readthedocs.io/en/stable/developer-guide/extensions/proxy-extensions/#configuration
> 2. Argo CD metrics server is not configured properly.
> 
> I suspect that this is caused by `#1` so please, ensure that the feature flag is enabled. If the proxy extension feature is enabled you should be able to see the following entry in the API Server logs: `Registering extensions... `

Thanks @leoluz !

I'll go about enabling it now. I assume I'll need to setup some proxy config ([as mentioned in the docs](https://argo-cd.readthedocs.io/en/stable/developer-guide/extensions/proxy-extensions/#configuration)), are there any examples of this anywhere so I'm not shooting in the dark?

**Comment by leoluz** [comment]
@harrywm Correct. You need this configuration in the `argocd-cm`
```
  extension.config: |-
    extensions:
      - name: metrics
        backend:
          services:
            - url: <METRICS_SERVER_URL>
```

And you need to authorize this extension in the `argocd-rbac-cm`:
```
p, role:readonly, extensions, invoke, metrics, allow
```

I will update the main docs in this repo to help future users about the required steps. Tks for pointing this out!

**Comment by harrywm** [comment]
Thanks so much @leoluz! Happy to review some docs changes as well, if you need any look over them from fresh eyes :)

**Comment by leoluz** [comment]
@harrywm here it is:
https://github.com/argoproj-labs/argocd-extension-metrics/pull/64/files

**Comment by ofirshaya** [comment]
I can confirm this works after the added information from @leoluz 

thank you!

just a disclaimer that the url should be along the lines of

`http://YOUR-INTERNAL-SVC-ADDRESS:9003
`
