### ISSUE TITLE
Can't make it work with Mimir

### ISSUE THREAD

**Issue by mcanevet** [argoproj-labs/argocd-extension-metrics#66]
I'm trying to make this extension work with [Grafana's Mimir](https://grafana.com/oss/mimir/) instead of vanilla Prometheus but somehow it does not work.
I have `Metric <metrics name> not available` in every dashboard.
Here is the Prometheus server URL I'm using: `http://mimir-query-frontend.mimir.svc.cluster.local:8080/prometheus`.

FTR:
- this Prometheus URL works fine as a Prometheus datasource for Grafana,
- I do not have any network policy that could prevent the traffic to  reach Mimir,
- I don't see any request in Mimir's query-frontend pod when I go to the "Metrics" tab in ArgoCD (while I can see the requests coming from Grafana when I browse the dashboards),

Could it be because I have a `/prometheus` path in the Prometheus server URL?

**Comment by Leegin-darknight** [comment]
@mcanevet Did you try passing the tenant ID as a header **X-Scope-OrgID**? I am not sure if this extension supports passing headers. @sarabala1979 Do we support this?

**Comment by mcanevet** [comment]
OK it actually works fine, I just forgot to escape `{{` when deploying the `ConfigMap` with helm.
