### ISSUE TITLE
No metrics to display

### ISSUE THREAD

**Issue by bomtan2000** [argoproj-labs/argocd-extension-metrics#67]
Please help me
<img width="890" alt="1" src="https://github.com/argoproj-labs/argocd-extension-metrics/assets/42080213/6e4de77d-24e7-41cd-ad04-e45947fc6ab3">
- config maps: argocd-cm
<img width="260" alt="image" src="https://github.com/argoproj-labs/argocd-extension-metrics/assets/42080213/e626702f-51b8-416d-9ce7-4be388581e6e">
- logs extension-metrics
<img width="583" alt="image" src="https://github.com/argoproj-labs/argocd-extension-metrics/assets/42080213/36e0da82-5d7a-41a5-9cc0-447b95338302">

**Comment by autokilla47** [comment]
+1
![image](https://github.com/argoproj-labs/argocd-extension-metrics/assets/49757910/e0452d20-3d9c-4bd9-8ffa-936b87353e67)

**Comment by autokilla47** [comment]
@bomtan2000 resolved? did you solve this problem?

**Comment by bomtan2000** [comment]
@autokilla47

I haven't solved it yet

**Comment by yalattas** [comment]
I am experiencing same issue, let me if you resolve it

**Comment by mcanevet** [comment]
For me it works with this fix: https://github.com/argoproj-labs/argocd-extension-metrics/pull/65/files

**Comment by leoluz** [comment]
Please double check if the typo fix in the doc provided by @mcanevet addresses the issue.

**Comment by r-pag** [comment]
I'm facing same issue. I'm almost give-up do configure it. Did someone solve the problem?

**Comment by bomtan2000** [comment]
i change file config maps: argocd-cm
<img width="259" alt="image" src="https://github.com/user-attachments/assets/5c217c95-2f74-4d92-aed7-cb6c84f4195e">

Tabs metrics argocd 
<img width="691" alt="image" src="https://github.com/user-attachments/assets/403d65e4-a132-4dc4-8ab7-e3b670c0a0a6">

**Comment by yalattas** [comment]
I already put this line. Yet, I have the following error
```
server time="2024-07-30T22:28:48Z" level=info msg="unauthorized extension request: unauthorized to invoke extension \"metrics\": rpc error: code = PermissionDenied desc = permission denied: extensions, invoke, metrics, sub: admin, iat: 2024-07-30T22:21:40Z"
```

What I am missing in my configs. I am using helm values

```
configs:
  cm:
    create: true
...
    extension.config: |-
      extensions:
        - name: metrics
          backend:
            services:
              - url: http://argocd-metrics-server:9003
```
@bomtan2000

**Comment by yalattas** [comment]
Just figured my issue. Permissions wasn't set correctly for `metrics` extension
Now I am facing different issue
![image](https://github.com/user-attachments/assets/37767a6f-b63f-4407-8510-56ef8313b761)

**Comment by r-pag** [comment]
I'm still receiving error trying to access metrics!!! I did all the tips and configs above, but didn`t solve it.

![image](https://github.com/user-attachments/assets/a19de565-05cc-42cd-bf61-984b0117b142)

**Comment by r-pag** [comment]
I have to point /extensions/metrics to metrics-server in my ingress configuration?

**Comment by r-pag** [comment]
When I set enableTLS: false on metrics-server, I cant't even see GET connections on pod, and receive error 502 Bad Gateway on UI interface.
If I set enableTLS: true, I get GET logs connections on pod, and receive 404 Not Found on UI interface.

**Comment by r-pag** [comment]
It seems when calling with uri /extensions/metrics is not working, I receive 404. When I call without that uri the metrics are ok, receiving 200.

![image](https://github.com/user-attachments/assets/bf6f51d3-221d-4e9b-91be-e4b3e2345ce6)

**Comment by AliKhyar** [comment]
+1

**Comment by HuTiuOnTheCloud** [comment]
@r-pag have u enable extension enable: true on argocd-server param ?
![image](https://github.com/user-attachments/assets/62f7bf31-a5f7-47a6-ab3c-5251cdebc782)
