### ISSUE TITLE
Time range Golden Signal Tabs

### ISSUE THREAD

**Issue by Jojoooo1** [argoproj-labs/argocd-extension-metrics#71]
Would you mind sharing how you have added the time range within the Golden Signal Tabs ?

![image](https://github.com/argoproj-labs/argocd-extension-metrics/assets/17641873/1f863ca6-0755-4ec6-9289-bbfd31bf18e1)

**Comment by Tchoupinax** [comment]
Hey @Jojoooo1,
You can add it in the config map, there is an exemple [here](https://github.com/argoproj-labs/argocd-extension-metrics/blob/a31b2b7ebda792331aaac9856f4af8d98a615af0/app/config.json#L105). Copy/paste the example worked :)

**Comment by Jojoooo1** [comment]
Thank you very much @Tchoupinax !
