### ISSUE TITLE
No Data in charts 

### ISSUE THREAD

**Issue by name814477** [argoproj-labs/argocd-extension-metrics#75]
hi,
Not showing any  Data related memory and traffic only cpu is visible. 
@crenshaw-dev & @leoluz 

![image](https://github.com/argoproj-labs/argocd-extension-metrics/assets/100115880/6104a547-fa5e-4aad-9fa8-e6f0e091b9f8)

**Logs:**

![image](https://github.com/argoproj-labs/argocd-extension-metrics/assets/100115880/90c0a83a-2bd2-41e1-a192-bd95d4ff8331)

**Comment by ahmadalkhansa** [comment]
I'm facing the same issue

**Comment by leoluz** [comment]
If you see at least one of the graphs rendered with data it means that the connectivity with Argo CD and the Metrics Server is working. For rendering cpu, memory and http related graphs in the dashboard we execute the query targeting the specific provider which in this case is Prometheus. Make sure that the query configured in the [configmap.yaml](https://github.com/argoproj-labs/argocd-extension-metrics/blob/a31b2b7ebda792331aaac9856f4af8d98a615af0/manifests/configmap.yaml#L45C24-L45C36) file returns valid data in Prometheus. You can use the Prometheus UI in the browser to test each query.

**Comment by ahmadalkhansa** [comment]
Thank you @leoluz! it was a query expression issue. For some reason, removing the "rate" function to query memory usage of containers solved the problem. All metrics related to HTTP did not exist so there was nothing to query there.

**Comment by name814477** [comment]
Thank you @leoluz and @ahmadalkhansa! It works
